# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd4667bdee643a324aafb1212cf2df9495258629d396ef252773e8ca1be2b0c2ccdf5530d6dbb06acf215c3236afa51c3f909ca2c2542c7a235f160c888bdbf2

test:
  secret_key_base: 7fb1faacb31650a8410474d15bc114e8939ce216d425213e979274a1009892035f6c1a63fc0edf074c600bd1aa5131f7b57f992d61001b2eeab3ead30fbd1f5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
